repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        name: black-format
        language_version: python3.9
        exclude: setup.py
        args: [--line-length=100]
  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        name: flake8-format
        exclude: setup.py
        args: [--max-line-length=100]